from typing import Any, Dict


AUTHOR_STYLE_TEMPLATES: Dict[str, Dict[str, Any]] = {
    "default": {
        "mode": "manual",
        "style_id": "default",
        "name": "默认风格",
        "description": "通用网络小说写作风格，强调清晰叙事、稳定节奏与可读性。",
        "features": ["通用叙事", "节奏稳定", "适配性强"],
        "narrative_pace": 5,
        "description_density": 5,
        "dialogue_ratio": 5,
        "emotional_intensity": 5,
        "guidelines": [
            "叙事清晰，避免辞藻堆砌",
            "场景、动作、对白保持均衡",
            "每章都有明确推进点",
            "结尾尽量留下继续阅读动机",
        ],
        "forbidden": ["避免大段空泛抒情", "避免无意义重复描写", "避免角色口吻完全同质化"],
        "tone_examples": ["语言自然流畅，兼顾剧情推进与阅读顺滑感。"],
    },
    "wuxia_jinyong": {
        "mode": "manual",
        "style_id": "wuxia_jinyong",
        "name": "金庸派",
        "description": "重人物群像、门派江湖、家国气与正统武侠叙事，语言典雅而不板滞。",
        "features": ["人物立体", "江湖氛围", "叙事稳健", "门派体系"],
        "narrative_pace": 5,
        "description_density": 7,
        "dialogue_ratio": 5,
        "emotional_intensity": 6,
        "guidelines": [
            "注重人物出身、性格、立场的层层展开",
            "江湖恩怨与家国背景可相互映照",
            "武打描写讲求招式、身法与气度并存",
            "对白应体现身份、教养与门派气质",
            "叙事厚重，避免轻浮网络腔",
        ],
        "forbidden": ["避免过于现代的网络口头禅", "避免无来由的装酷式短句堆叠", "避免只顾打斗不顾人物缘起"],
        "tone_examples": ["夜色沉沉，长街寂寂，惟有檐角风铃轻响，似也在替旧日恩仇低声叹息。"],
    },
    "wuxia_gulong": {
        "mode": "manual",
        "style_id": "wuxia_gulong",
        "name": "古龙派",
        "description": "强调凝练短句、留白、冷峻气质与戏剧张力，人物常带宿命感与传奇感。",
        "features": ["语言凝练", "气质冷峻", "戏剧感强", "留白锋利"],
        "narrative_pace": 7,
        "description_density": 4,
        "dialogue_ratio": 7,
        "emotional_intensity": 6,
        "guidelines": [
            "多用短句与断裂节奏制造压迫感",
            "关键情绪不要说满，要留白",
            "对白要像交锋，带刺、带锋、带机锋",
            "人物出场应具有强烈镜头感与传奇感",
            "避免冗长背景说明，用细节反推人物处境",
        ],
        "forbidden": ["避免长篇背景讲解", "避免语言过于板正厚重", "避免把人物心理解释得过满"],
        "tone_examples": ["灯很冷。刀也很冷。可他的眼睛，比刀更冷。"],
    },
    "romance_qiongyao": {
        "mode": "manual",
        "style_id": "romance_qiongyao",
        "name": "琼瑶派",
        "description": "强调情感起伏、人物关系纠葛与抒情表达，情绪浓烈而外放。",
        "features": ["情感浓烈", "关系推动", "抒情表达", "冲突外显"],
        "narrative_pace": 5,
        "description_density": 6,
        "dialogue_ratio": 6,
        "emotional_intensity": 9,
        "guidelines": [
            "把人物爱与痛写到明处，但保持真挚",
            "对白要能推动关系变化与情绪爆发",
            "环境可作为情绪映衬，增强抒情感",
            "冲突多从误会、选择、牺牲中产生",
            "重视人物内心独白与感情波澜",
        ],
        "forbidden": ["避免冷硬纪实腔", "避免把情绪写得过于克制而失去张力", "避免只谈剧情推进不写关系变化"],
        "tone_examples": ["她望着他，眼里仿佛盛着一整场未曾落尽的雨，哀伤而炽热。"],
    },
    "wuxia_liangyusheng": {
        "mode": "manual",
        "style_id": "wuxia_liangyusheng",
        "name": "梁羽生派",
        "description": "诗意较强，兼重历史感、侠义精神与人物风骨，气质清正舒展。",
        "features": ["诗意笔法", "历史气息", "侠义风骨", "气质清正"],
        "narrative_pace": 4,
        "description_density": 7,
        "dialogue_ratio": 4,
        "emotional_intensity": 5,
        "guidelines": [
            "语言可稍带古典韵味，但要保持流畅",
            "突出侠义、风骨与时代背景的关联",
            "场景描写可更舒展，更有画面感",
            "人物价值选择要能体现精神立场",
        ],
        "forbidden": ["避免语言过于轻佻", "避免只写奇情不写风骨", "避免历史背景完全虚化"],
        "tone_examples": ["长风卷过古道，黄叶满地，行人一骑西来，仿佛也裹着旧时山河的寒意。"],
    },
    "wuxia_wenruian": {
        "mode": "manual",
        "style_id": "wuxia_wenruian",
        "name": "温瑞安派",
        "description": "文字灵动跳脱，节奏快，意象强，招式与情绪常并行爆发。",
        "features": ["文字灵动", "节奏明快", "意象强烈", "爆发感足"],
        "narrative_pace": 8,
        "description_density": 6,
        "dialogue_ratio": 5,
        "emotional_intensity": 7,
        "guidelines": [
            "招式描写与心理波动同步推进",
            "句式可更富变化，制造冲击感",
            "意象应鲜明，增强速度与力量感",
            "情节推进保持锐利，不拖泥带水",
        ],
        "forbidden": ["避免平铺直叙到底", "避免动作场面缺少节奏变化", "避免意象疲软无爆发点"],
        "tone_examples": ["剑起时，风像碎了；人未退，心已惊。"],
    },
    "literary_zhangailing": {
        "mode": "manual",
        "style_id": "literary_zhangailing",
        "name": "张爱玲派",
        "description": "擅长细腻世情、人物幽微心理与带冷感的精致观察，语言华美而克制。",
        "features": ["世情观察", "心理细腻", "冷感华美", "细节锋利"],
        "narrative_pace": 3,
        "description_density": 8,
        "dialogue_ratio": 4,
        "emotional_intensity": 5,
        "guidelines": [
            "重视细节中的阶层、欲望与人情冷暖",
            "情绪不宜过喊，要在克制中见锋芒",
            "多写人物表面动作下的真实心意",
            "环境与服饰细节可折射人物处境",
        ],
        "forbidden": ["避免热血爽文式直白宣泄", "避免粗线条人物塑造", "避免缺少世情观察的空抒情"],
        "tone_examples": ["她低下头去，像一朵颜色过分浓艳的花，忽然在灯影里暗了一暗。"],
    },
    "realism_moyan": {
        "mode": "manual",
        "style_id": "realism_moyan",
        "name": "莫言派",
        "description": "具有强烈生命力与乡土感，现实与荒诞交织，感官描写饱满。",
        "features": ["生命力强", "乡土气息", "荒诞现实", "感官饱满"],
        "narrative_pace": 6,
        "description_density": 8,
        "dialogue_ratio": 4,
        "emotional_intensity": 7,
        "guidelines": [
            "画面感要强，气味、颜色、声音都可入文",
            "现实叙事中可夹带夸张和荒诞感",
            "人物生命力要旺盛，不写成扁平符号",
            "语言可带泥土气与野性，不必过于修饰",
        ],
        "forbidden": ["避免语言过于精致纤弱", "避免人物失去粗粝生命力", "避免场景缺少感官触感"],
        "tone_examples": ["风从土坡上滚下来，带着牲口气、草根气，还有太阳烤裂黄土后的焦苦味。"],
    },
    "web_heianhuolong": {
        "mode": "manual",
        "style_id": "web_heianhuolong",
        "name": "黑暗火龙派",
        "description": "偏升级流与修炼成长线，强调稳步变强、战斗推进、资源争夺和连续爽点回报。",
        "features": ["升级流", "修炼推进", "战斗密集", "爽点持续"],
        "narrative_pace": 8,
        "description_density": 5,
        "dialogue_ratio": 4,
        "emotional_intensity": 6,
        "guidelines": [
            "主线以成长、突破、对抗为核心持续推进",
            "每章尽量给出明确收益，如境界、资源、地位或战绩提升",
            "战斗描写要清楚直接，突出压制、反制与逆转",
            "敌我强弱对比鲜明，冲突目标明确",
        ],
        "forbidden": ["避免长时间停留在无推进的日常", "避免修炼体系模糊不清", "避免爽点铺垫过长而迟迟不兑现"],
        "tone_examples": ["真元轰然运转，林辰只觉得体内关窍一寸寸松动，下一瞬，压制许久的壁障终于被一剑劈开。"],
    },
    "web_chendong": {
        "mode": "manual",
        "style_id": "web_chendong",
        "name": "辰东派",
        "description": "擅长宏大世界观、远古秘辛、热血大战与史诗感，常把个人命运放进大时代洪流。",
        "features": ["世界宏大", "秘辛感强", "史诗热血", "远古悬念"],
        "narrative_pace": 7,
        "description_density": 7,
        "dialogue_ratio": 4,
        "emotional_intensity": 7,
        "guidelines": [
            "场面要有天地格局与时代纵深感",
            "适合埋设远古秘密、宿命因果与长线伏笔",
            "大战描写要兼顾气势、压迫感与悲壮感",
            "主角成长要与更大格局绑定",
        ],
        "forbidden": ["避免世界观显得过小", "避免只有个人恩怨没有时代纵深", "避免战斗缺乏恢弘感"],
        "tone_examples": ["苍穹尽头，古老战旗猎猎作响，仿佛一段被尘封万载的血色岁月，正在此刻重新苏醒。"],
    },
    "web_tiancantudou": {
        "mode": "manual",
        "style_id": "web_tiancantudou",
        "name": "天蚕土豆派",
        "description": "强调清晰升级体系、热血逆袭、资源争夺与阶段性高光爆发，阅读节奏顺畅。",
        "features": ["体系清晰", "逆袭热血", "阶段爆发", "阅读顺滑"],
        "narrative_pace": 8,
        "description_density": 5,
        "dialogue_ratio": 5,
        "emotional_intensity": 7,
        "guidelines": [
            "升级体系与层级差距必须清晰可感",
            "用压制—隐忍—爆发的结构制造爽感",
            "重要战斗要有明确高潮点和反转点",
            "角色目标清晰，推进感要强",
        ],
        "forbidden": ["避免升级体系混乱", "避免爽点来得太突然缺少铺垫", "避免主角长期被动无成长反馈"],
        "tone_examples": ["当那股力量自气海深处暴涌而出时，先前所有轻蔑的目光，都在这一刻化为了惊骇。"],
    },
    "web_wochi_xihongshi": {
        "mode": "manual",
        "style_id": "web_wochi_xihongshi",
        "name": "我吃西红柿派",
        "description": "节奏稳、结构清楚，长于成长主线、修炼体系、目标驱动与正向反馈，阅读体验流畅。",
        "features": ["结构清楚", "成长稳健", "目标驱动", "反馈明确"],
        "narrative_pace": 6,
        "description_density": 5,
        "dialogue_ratio": 4,
        "emotional_intensity": 5,
        "guidelines": [
            "情节推进讲究层层升级、阶段达成",
            "目标和阻碍要清晰，让读者能持续跟随",
            "修炼、冒险、战斗三者保持均衡",
            "语言直接清爽，不刻意堆砌辞藻",
        ],
        "forbidden": ["避免结构混乱", "避免支线喧宾夺主", "避免情节长时间原地踏步"],
        "tone_examples": ["他很清楚，想要走得更远，眼前这一步就绝不能退。唯有跨过去，才能看到更高处的风景。"],
    },
    "web_ergen": {
        "mode": "manual",
        "style_id": "web_ergen",
        "name": "耳根派",
        "description": "兼具修真成长、宿命感、孤独感与哲思气质，擅长把人物心境和世界规则结合起来。",
        "features": ["修真宿命", "心境描写", "孤独感", "哲思意味"],
        "narrative_pace": 5,
        "description_density": 7,
        "dialogue_ratio": 4,
        "emotional_intensity": 6,
        "guidelines": [
            "修炼不只是力量提升，也要体现心境变化",
            "人物常带孤独、执念或命运压迫感",
            "世界规则与人物选择互相映照",
            "语言可带少量苍凉感与追问意味",
        ],
        "forbidden": ["避免纯爽文式无代价升级", "避免人物心境完全空白", "避免修真世界缺少命运感与规则感"],
        "tone_examples": ["他站在风里，忽然明白这一路失去的，不只是故人，还有那个曾经会回头张望的自己。"],
    },
    "web_tangjia_sanshao": {
        "mode": "manual",
        "style_id": "web_tangjia_sanshao",
        "name": "唐家三少派",
        "description": "强调少年热血、团队羁绊、成长试炼与正向情感驱动，适合明亮型长线成长故事。",
        "features": ["少年热血", "团队羁绊", "成长试炼", "情感正向"],
        "narrative_pace": 7,
        "description_density": 5,
        "dialogue_ratio": 6,
        "emotional_intensity": 7,
        "guidelines": [
            "突出伙伴关系、信念与共同成长",
            "冲突中强调坚持、守护、责任等主题",
            "升级与试炼要能带来人格成长",
            "语言积极明快，适合少年感叙事",
        ],
        "forbidden": ["避免整体基调过于阴郁沉重", "避免团队关系缺少互动与情感支撑", "避免成长线只有力量没有精神成长"],
        "tone_examples": ["少年攥紧了拳，眼里的光却比星辰更亮，因为他知道，自己从来不是一个人在战斗。"],
    },
}


def list_author_styles() -> list[Dict[str, Any]]:
    return list(AUTHOR_STYLE_TEMPLATES.values())


def get_author_style(style_id: str | None) -> Dict[str, Any]:
    return AUTHOR_STYLE_TEMPLATES.get(style_id or "default", AUTHOR_STYLE_TEMPLATES["default"])


def apply_style_strength(style: Dict[str, Any], strength: str | None) -> Dict[str, Any]:
    strength = strength or "medium"
    style = dict(style)
    style["strength"] = strength
    strength_map = {
        "light": "轻度风格化：保留该作家气质，但不要过度模仿，仍以可读性和兼容性优先。",
        "medium": "中度风格化：明显体现该作家风格特征，但保持故事自然流畅。",
        "strong": "强风格化：尽可能突出该作家笔法、语感、节奏和结构习惯，但仍避免机械模仿。",
    }
    style["strength_instruction"] = strength_map.get(strength, strength_map["medium"])
    return style
